#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Don't concern yourself it it was lo that came up
if [ "$IFACE" != eth0 ]; then
	exit 0
fi

# Make sure the daemon is running, no need to bother otherwise
if (( $(ps -ef | grep -v grep | grep tcpdump | wc -l) > 0 )); then
  echo "TCP Logging appears to be turned on. Let's make sure this interface is logging."
  if (( $(ps -ef | grep -v grep | grep $IFACE | wc -l) > 0 )); then
    echo "Interface is being logged already."
  else
    echo "Interface is not being logged, kicking logging service."
    systemctl restart tcplogger
  fi
fi

